name: JVM Test

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  jvm-test:
    name: JVM Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run JVM tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: :fhir-model:jvmTest --rerun-tasks --stacktrace
